require_relative "config/database"
require_relative "config/constants"
require_relative "models/parking_lot"
require_relative "models/vehicle"
require_relative "models/history"
require_relative "solution"
require "terminal-table"